config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'orderitems#index', as: :cart
  put 'cart/update_orderitems', to: 'orderitems#update_orderitems', as: 'cart_update_orderitems'
  put 'cart/apply_discount', to: 'orders#apply_discount', as: 'cart_apply_discount'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :orderitems, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index, :show, :edit, :update] do
    get 'cancel', on: :member
  end
  resources :checkout, only: [:show, :update]

  devise_for :admins, only: :sessions
  devise_for :customers, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "customers", :sessions => "sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :customers

    root :to => 'books#index'

end

app/views/cart/_cart_row.html.haml
.well
  .row
    .table{:style => "word-wrap: break-word"}
      %tr
        .col-xs-2
          %td
            = image_tag book.image_url(:mini)
        .col-xs-7
          %td
            .text-center
              BOOK
              %h4= book.title
            #{book.description}
        .col-xs-1
          %td
            .text-right
              PRICE
            %h4.text-right 
              = number_to_currency orderitem.unit_price
      = f.fields_for 'orderitems[]', orderitem do |oi|
        .col-xs-1 
          %td
            .text-center
              QTY
            #quantity
              = oi.number_field :quantity, value: orderitem.quantity.to_i, class: "form-control", min: 1
            = oi.hidden_field :book_id, {value: book.id}
        .col-xs-1
          %td
            TOTAL
            %h4
              = number_to_currency orderitem.price
            .text-right  
              = link_to "Delete", orderitem, { data: { confirm: "Are you shure you wish to delete the book '#{orderitem.book.title }' from your cart?" }, method: :delete, :url => orderitem_path(orderitem.id), class: "btn btn-danger" }
        
        

app/views/cart/_shopping_cart.html.haml
- if @orderitems.size == 0
  .text-center
    %p 
      There are no items in your shopping cart. Please 
      = link_to "go back and choose", root_path
- else
  = form_for current_order, :url => cart_update_orderitems_path, :html => { method: :put } do |f|
    - @orderitems.sort.each do |orderitem|
      = render 'cart/cart_row', book: orderitem.book, orderitem: orderitem, f: f
    .text-right
      = f.submit "Update Orderitems Quantity", class: "btn btn-primary"
  .div  
    %h3.text-right
      Subtotal:
      = number_to_currency current_order.total_price
    .text-center
      = form_for current_order, :url => cart_apply_discount_path(current_order.id), html: { method: :put } do |f|
        = f.text_field :coupone_code, placeholder: "Coupone Code", value: ""
        = f.submit "GET DISCOUNT", class: "btn btn-primary"
      = link_to "Check Out", checkout_path(Checkout.form_steps.first), class: "btn btn-primary"
      = link_to "Back to shop", root_path, class: "btn btn-primary"
 

app/views/cart/show.html.haml
.shopping-cart
  = render "cart/shopping_cart"