config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'orderitems#index', as: :cart
  put 'cart/update_orderitems', to: 'orderitems#update_orderitems', as: 'cart_update_orderitems'
  put 'cart/apply_discount', to: 'orders#apply_discount', as: 'cart_apply_discount'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :orderitems, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index, :show, :edit, :update] do
    get 'cancel', on: :member
  end
  resources :checkout, only: [:show, :update]

  devise_for :admins, only: :sessions
  devise_for :customers, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "customers", :sessions => "sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :customers

    root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :price, :title, :description, :bookinstock, presence: true

    has_many :orderitems
    has_many :ratings
    belongs_to :author
    belongs_to :category

  before_save :set_small_description

  def self.bestsellers(count)
    joins(:orderitems).group('books.id').order("sum(quantity) DESC").limit(count)
  end
  
  private
  def set_small_description
    self.small_description = "#{self.description.first(150)}..."
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource only: :show

  def index
    authorize! :index, Book
    @books = Book.bestsellers(3).accessible_by(current_ability)
  end

  def show
    @orderitem = current_order.orderitems.build
    @ratings = @book.ratings
  end
end

app/views/books/_book_row.html.haml
.well
  .row
    %h4= book.title
    .col-xs-3
      = image_tag book.image_url
    .col-xs-7{:style => "word-wrap: break-word"}
      %p.text-left= book.description
    .col-xs-2
      = form_for @orderitem, :url => orderitems_path do |f|
        %h4.text-right 
          Unit Price:
          = number_to_currency book.price
        .input-group
          = f.number_field :quantity, value: 1, min: 1, class: "form-control", min: 1
          .input-group-btn
            = f.hidden_field :book_id, {value: book.id}
            = f.submit "Add to Cart", class: "btn btn-primary"

app/views/books/_books_row.html.haml
.well
  .row
    .col-xs-4
      = image_tag book.image_url
      %h4= book.title
    %span
    .col-xs-5.text-left
      %p{:style => "word-wrap: break-word"}
        = book.small_description
    .col-xs-3
      %h4.text-right 
        Unit Price:
        = number_to_currency book.price
      .text-center  
        = link_to "See Details", book_path(book.id), class: "btn btn-primary"

app/views/books/_review.html.haml
.row
  .col-xs-4
    Rating:
    #{rating.rating} / 5
.well
  .row
    .col-xs-6.col-xs-offset-1.text-left{:style => "word-wrap: break-word"}   
      %h4
        Review from #{rating.rater_name}:
      %p
        = rating.review

app/views/books/index.html.haml
%h3.text-center 
  Books for sale
  .row
    .col-xs-8.col-xs-offset-2
      #bestsellers.owl-carousel.owl-theme
        - @books.each do |book|
          .item
            = render "books_row", book: book

app/views/books/show.html.haml
%h3.text-center 
  Full Information
  .row
    .col-xs-12
      = render "book_row", book: @book, orderitem: @orderitem
  .row
    %h4
      Reviews:
      = link_to "(Add new Review)", new_book_rating_path(@book.id)
    - @ratings.each do |rating|
      - if rating.approved?
        = render "review", rating: rating