config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'orderitems#index', as: :cart
  put 'cart/update_orderitems', to: 'orderitems#update_orderitems', as: 'cart_update_orderitems'
  put 'cart/apply_discount', to: 'orders#apply_discount', as: 'cart_apply_discount'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :orderitems, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index, :show, :edit, :update] do
    get 'cancel', on: :member
  end
  resources :checkout, only: [:show, :update]

  devise_for :admins, only: :sessions
  devise_for :customers, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "customers", :sessions => "sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :customers

    root :to => 'books#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :title, presence: true, uniqueness: true

	has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @books = Book.all
  end

  def show
    @books = @category.books
  end
end

app/views/categories/_categories_row.html.haml
.well
  = link_to "#{category.title}", category_path(category.id)

app/views/categories/_category_row.html.haml
.col-xs-6{:style => "height:auto; overflow: auto"}
  .thumbnail{:style => "word-wrap: break-word"}
    = image_tag book.image_url
    %h3= book.title
    %p.text-left= book.small_description
    %h4 
      Unit Price:
      = number_to_currency book.price
    .input-group-btn
      = link_to "See Details", book_path(book.id), class: "btn btn-primary"

app/views/categories/index.html.haml
%h3.text-left
  Shop
.row
  .col-xs-8.text-center
    - @books.each do |book|
      = render "category_row", book: book
  .col-xs-3.text-center
    %h3
      Shop by Categories:
    - @categories.each do |category|
      = render "categories_row", category: category

app/views/categories/show.html.haml
%h3.text-center
  Category: #{@category.title}
.row
  .col-xs-8.col-xs-offset-2.text-center
    - @books.each do |book|
      = render "category_row", book: book