config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'orderitems#index', as: :cart
  put 'cart/update_orderitems', to: 'orderitems#update_orderitems', as: 'cart_update_orderitems'
  put 'cart/apply_discount', to: 'orders#apply_discount', as: 'cart_apply_discount'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :orderitems, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index, :show, :edit, :update] do
    get 'cancel', on: :member
  end
  resources :checkout, only: [:show, :update]

  devise_for :admins, only: :sessions
  devise_for :customers, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "customers", :sessions => "sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :customers

    root :to => 'books#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AmazonStore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = nav_bar static: :top, brand: "Happy Book store :)", responsive: true do
      = menu_group do
        = menu_item "Home", root_path
        = menu_divider
        = menu_item "Categories", categories_path
      %ul.nav.navbar-nav
        %li
          %a.cart{:href => cart_path}
            .i.fa.fa-shopping-cart.fa-2x
            - if current_order.orderitems.size == 0
              .badge empty
            - else
              .badge #{current_order.calculate_books_quantity} book
              .badge #{number_to_currency current_order.total_price}
      = menu_group pull: :right do
        - if current_customer
          = menu_item "Orders", orders_path
          = menu_item "Settings", edit_customer_registration_path
          = menu_item "Log Out", destroy_customer_session_path
        - else
          = menu_item "Log In", new_customer_session_path 
    .container
      .row
        = bootstrap_flash 
        = yield
  